server:
  port: 9527
spring:
  application:
    name: cloud-getaway
  cloud:
    gateway:
      routes:
        - id: payment_touth
          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**
eureka:
  instance:
    hostname: cloud-geteway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka