server:
  port: 9527
spring:
  application:
    name: cloud-getaway
eureka:
  instance:
    hostname: cloud-geteway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka